import { Router } from 'express';
import { authRoutes } from '../modules/auth/auth.routes.js';
import { usersRoutes } from '../modules/users/users.routes.js';
import { donationsRoutes } from '../modules/donations/donations.routes.js';
import { matchingRoutes } from '../modules/matching/matching.routes.js';
import { logisticsRoutes } from '../modules/logistics/logistics.routes.js';
import { analyticsRoutes } from '../modules/analytics/analytics.routes.js';
import { financeRoutes } from '../modules/finance/finance.routes.js';
import { adminRoutes } from '../modules/admin/admin.routes.js';
import { auditRoutes } from '../modules/audit/audit.routes.js';
import { intelligenceRoutes } from '../modules/intelligence/intelligence.routes.js';
import { automationRoutes } from '../modules/automation/automation.routes.js';
import { fraudRoutes } from '../modules/fraud/fraud.routes.js';
import { tenantsRoutes } from '../modules/tenants/tenants.routes.js';
import { csrRoutes } from '../modules/csr/csr.routes.js';
import { warehousesRoutes } from '../modules/warehouses/warehouses.routes.js';
import { gamificationRoutes } from '../modules/gamification/gamification.routes.js';
import { botsRoutes } from '../modules/bots/bots.routes.js';
import { ngosRoutes } from '../modules/ngos/ngos.routes.js';

export const router = Router();

router.get('/health', (_req, res) => res.json({ success: true, service: 'api-gateway' }));
router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/donations', donationsRoutes);
router.use('/matching', matchingRoutes);
router.use('/logistics', logisticsRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/finance', financeRoutes);
router.use('/admin', adminRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/ngos', ngosRoutes);
router.use('/intelligence', intelligenceRoutes);
router.use('/automation', automationRoutes);
router.use('/fraud', fraudRoutes);
router.use('/tenants', tenantsRoutes);
router.use('/csr', csrRoutes);
router.use('/warehouses', warehousesRoutes);
router.use('/gamification', gamificationRoutes);
router.use('/bots', botsRoutes);
